/** Generates ENHANCEMENTS.docx — running idea log, updated as ideas surface. */
import { h1, note, p, table, titlePage, TODAY, writeDoc } from "./helpers.mjs";

await writeDoc("ENHANCEMENTS.docx", [
  ...titlePage("Enhancements Log", "Investment Research Dashboard", TODAY),
  p("Running list of enhancement ideas. Logged the moment they come up (mine or Claude's); moved to Implemented when built."),

  h1("Implemented"),
  table(["Idea", "Date", "Notes"], [
    ["Portfolio assessment & optimization for the user's two Transamerica Retirement accounts", "2026-08-04", "Epic G shipped: holdings + fund menu ingested (manual entry), held funds scored against menu alternatives, within-menu swap suggestions with real annual-savings estimates. Both accounts reachable via an account switcher on /portfolio."],
    ["News/current-events influence in assessments, explicitly called out", "2026-08-04", "Two-layer assessment shipped: deterministic factor scores (Screener/Watchlist) + a Claude-written Event Impact narrative per account (G5), citing upcoming FOMC/CPI events. Displayed on the Portfolio and account-detail pages."],
    ["LLM narrative layer (Claude API) — summarize news/filings per holding", "2026-08-04", "Shipped as the G5 Event Impact Assessment narrative. Explains only; never alters scores. (Was being generated and silently discarded — fixed 2026-08-05 to actually display.)"],
    ["Phone access via Vercel deployment", "2026-08-04", "Live in production on Vercel (Turso DB, daily cron refresh)."],
    ["Watchlist accepts a company name, not just a ticker (\"Tesla\" resolves to TSLA)", "2026-08-04", "addToWatchlist() resolves free text via the equity provider's symbol search before ever writing to the DB; rejects unmatched input instead of creating a fake instrument. Includes a cleanup tool (Admin > Delete Instrument) for garbage symbols created before this existed."],
  ], { widths: [40, 14, 46] }),

  h1("Not Yet Implemented"),
  table(["Idea", "Raised", "Notes"], [
    ["Aggregator sync for account holdings (Plaid / SnapTrade)", "2026-08-03", "Deferred alternative to manual entry: cost, third-party credential sharing, and spotty Transamerica retirement coverage. Revisit if manual updates become a chore."],
    ["Paid data provider upgrade (FMP / Polygon / Tiingo)", "2026-08-03", "Planned-for by design: env-driven provider selection (B7). Trigger: yahoo-finance2 breakage or need for deeper fundamentals/real-time."],
    ["Backtesting engine over persisted factor-score history", "2026-08-03", "factor_scores table is designed to enable this; consider DuckDB for the analytics if data grows. Factor scores now actually persist (fixed 2026-08-05), so there's real history to backtest against going forward."],
    ["Individual bond data (CUSIP-level)", "2026-08-03", "Deferred — requires premium data; v1 uses yield curve + bond-ETF proxies."],
    ["Real-time quotes", "2026-08-03", "Requires paid provider; free tier is delayed/EOD."],
    ["Portfolio tracking (positions, cost basis, P&L)", "2026-08-03", "Out of v1 scope — dashboard is research-first; natural v2 candidate."],
    ["Market indices/crypto data on the Markets & Dashboard pages (SPY/QQQ/IWM/BTC/ETH/USDT)", "2026-08-05", "Pipeline now persists prices for whatever's on the watchlist, but these specific index/crypto instruments are never seeded, so the cards stay correctly empty. Needs a seed step (Admin action) to populate them."],
  ], { widths: [40, 14, 46] }),

  h1("Rejected / Deferred"),
  table(["Idea", "Date", "Why"], [
    ["LLM-driven scoring (LLM forms the investment view)", "2026-08-03", "Rejected for v1: not auditable or backtestable; LLMs can be confidently wrong about numbers. Deterministic rules + LLM narrative chosen instead."],
    ["better-sqlite3 file database", "2026-08-03", "Rejected: incompatible with Vercel's ephemeral filesystem. libSQL/Turso chosen — same semantics, deployable."],
  ], { widths: [40, 14, 46] }),
  note("Generated by scripts/gen-docs/enhancements.mjs."),
]);
