/** Generates ENHANCEMENTS.docx — running idea log, updated as ideas surface. */
import { h1, note, p, table, titlePage, TODAY, writeDoc } from "./helpers.mjs";

await writeDoc("ENHANCEMENTS.docx", [
  ...titlePage("Enhancements Log", "Investment Research Dashboard", TODAY),
  p("Running list of enhancement ideas. Logged the moment they come up (mine or Claude's); moved to Implemented when built."),

  h1("Implemented"),
  table(["Idea", "Date", "Notes"], [
    ["—", "", "Nothing yet — v1 is under construction."],
  ], { widths: [40, 14, 46] }),

  h1("Not Yet Implemented"),
  table(["Idea", "Raised", "Notes"], [
    ["Paid data provider upgrade (FMP / Polygon / Tiingo)", "2026-08-03", "Planned-for by design: env-driven provider selection (B7). Trigger: yahoo-finance2 breakage or need for deeper fundamentals/real-time."],
    ["LLM narrative layer (Claude API) — summarize news/filings per holding", "2026-08-03", "Scheduled as Epic E3. Explains only; never alters scores."],
    ["Backtesting engine over persisted factor-score history", "2026-08-03", "factor_scores table is designed to enable this; consider DuckDB for the analytics if data grows."],
    ["Individual bond data (CUSIP-level)", "2026-08-03", "Deferred — requires premium data; v1 uses yield curve + bond-ETF proxies."],
    ["Phone access via Vercel deployment", "2026-08-03", "Scheduled as Epic F1 (Turso + cron refresh + access protection)."],
    ["Real-time quotes", "2026-08-03", "Requires paid provider; free tier is delayed/EOD."],
    ["Portfolio tracking (positions, cost basis, P&L)", "2026-08-03", "Out of v1 scope — dashboard is research-first; natural v2 candidate."],
  ], { widths: [40, 14, 46] }),

  h1("Rejected / Deferred"),
  table(["Idea", "Date", "Why"], [
    ["LLM-driven scoring (LLM forms the investment view)", "2026-08-03", "Rejected for v1: not auditable or backtestable; LLMs can be confidently wrong about numbers. Deterministic rules + LLM narrative chosen instead."],
    ["better-sqlite3 file database", "2026-08-03", "Rejected: incompatible with Vercel's ephemeral filesystem. libSQL/Turso chosen — same semantics, deployable."],
  ], { widths: [40, 14, 46] }),
  note("Generated by scripts/gen-docs/enhancements.mjs."),
]);
