/** Generates USER_GUIDE.docx — written for a non-technical reader. */
import { bullet, h1, h2, note, p, titlePage, TODAY, writeDoc } from "./helpers.mjs";

await writeDoc("USER_GUIDE.docx", [
  ...titlePage("User Guide", "Investment Research Dashboard", TODAY),

  h1("What this app does"),
  p("This is your personal investment research desk. It automatically gathers up-to-date prices, company financials, economic data, and news for stocks, ETFs, cryptocurrencies, and bonds — then highlights which investments look most promising based on clear, explainable rules you can inspect and tune. It is a research aid: it organizes evidence and points at candidates, but the decisions stay with you. Nothing in it is investment advice."),

  h1("Current status"),
  p("The app is in early construction. The foundation (project setup, quality checks, and this documentation) is complete; data connections and screens are being built next. This guide grows a section per feature as each one lands — everything below describes what the finished v1 will do."),

  h1("What v1 will let you do"),
  h2("See the market at a glance"),
  bullet("A dashboard with major indexes, interest-rate conditions, and a crypto snapshot — refreshed automatically, each number stamped with when it was last updated."),
  h2("Track what you own or watch"),
  bullet("A watchlist where you add any stock, ETF, or coin and see its price, key financials, and score in one table."),
  h2("Find promising investments"),
  bullet("A screener that scores investments 0–100 on four ideas: is it reasonably priced (Valuation), is the business growing (Growth), is it a well-run business (Quality), and is the price trending the right way (Momentum)."),
  bullet("Click any score to see exactly why — every number behind it is shown. If data is missing, the app says so instead of guessing."),
  bullet("Preset lenses let you emphasize what matters to you: Balanced, Value, Growth, or Quality."),
  h2("Stay informed"),
  bullet("A news feed tagged to your watchlist tickers, plus a calendar of earnings dates and economic releases."),
  bullet("Later: short plain-English summaries of the news around each holding — clearly separated from the scores, which are always pure arithmetic."),

  h1("Good to know"),
  bullet("Data comes from free sources and can be 15 minutes to a day delayed — fine for research, not for day-trading."),
  bullet("The app runs on your Mac; a web version you can open from your phone is planned."),
  bullet("A high score means 'worth a closer look by the rules you chose,' not 'guaranteed winner.' Markets humble everyone."),
  note("Generated by scripts/gen-docs/user-guide.mjs."),
]);
